services:
  - type: web
    name: django-auth-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn p1.wsgi:application
    envVars:
      - key: DB_ENGINE
        value: django.db.backends.mysql
      - key: DB_NAME
        value: p2_db
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: S@16112001
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: "3306"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,login-form.onrender.com
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: 4912f38f02773f
      - key: EMAIL_HOST_PASSWORD
        value: c0ffbad12a667f
      - key: DEFAULT_FROM_EMAIL
        value: noreply@example.com
